apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: g2m4ey5pf-go
  janus-idp.io/tekton: g2m4ey5pf-go
  backstage.io/kubernetes-id: g2m4ey5pf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g2m4ey5pf-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
